[project]
name = "ui-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "football-common",
    "langchain==0.3.27",
    "pandas>=2.2,<3",
    "streamlit==1.48.1",
    "trino==0.336.0",
]

[project.scripts]
ui-streamlit = "ui_streamlit.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ui_streamlit"]
