services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports: ["9000:9000", "9001:9001"]
    volumes: ["../data/minio:/data"]

  mc:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z-cpuv1
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 admin password) do sleep 1; done;
      mc mb -p minio/warehouse || true;
      tail -f /dev/null
      "

  rest:
    image: apache/iceberg-rest-fixture:latest
    environment:
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_PATH_STYLE_ACCESS: "true"
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
    ports: ["8181:8181"]
    depends_on: [minio]

  trino:
    image: trinodb/trino:476
    depends_on: [rest, minio]
    ports: ["8081:8080"]
    volumes:
      - ../catalog/trino:/etc/trino/catalog
