services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports: ["9000:9000", "9001:9001"]
    volumes: ["../data/minio:/data"]

  mc:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z-cpuv1
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 admin password) do sleep 1; done;
      mc mb -p minio/warehouse || true;
      # uncomment to wipe on every start:
      # mc rm -r --force minio/warehouse/* || true;
      tail -f /dev/null
      "

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - ../data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [postgres]
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin

  metastore:
    image: apache/hive:standalone-metastore-4.1.0
    depends_on: [postgres]
    environment:
      METASTORE_DB_HOST: postgres
      METASTORE_DB_NAME: metastore_db
      METASTORE_DB_USER: hive
      METASTORE_DB_PASS: password
      METASTORE_DB_DRIVER: org.postgresql.Driver
      METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/metastore_db
    volumes:
      - ./postgresql.jar:/opt/hive-metastore/lib/postgresql.jar
      - ./metastore-site.xml:/opt/hive-metastore/conf/metastore-site.xml
    ports: ["9083:9083"]

  trino:
    image: trinodb/trino:476
    depends_on: [metastore, minio]
    ports: ["8081:8080"]
    volumes:
      - ../catalog/trino:/etc/trino/catalog
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      S3_ENDPOINT: http://minio:9000
      S3_PATH_STYLE_ACCESS: "true"
      JAVA_TOOL_OPTIONS: "-Daws.region=us-east-1"

  spark:
    image: tabulario/spark-iceberg:latest
    container_name: spark-iceberg
    depends_on: [metastore, minio]
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
      SPARK_LOG_LEVEL: WARN
    volumes:
      - ../notebooks:/home/iceberg/notebooks
    ports:
      - "8888:8888" # Jupyter (if you start it)
      - "8082:8080" # Spark UI (if you use it)
    entrypoint: ["sleep", "infinity"]
